# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: "myMac"

resources:
  containers:
  - container: mysql
    image: mysql
    ports:
    - 3306:3306
  - container: redis
    image: redis
    ports:
    - 6379:6379

services:
  mysql: mysql
  redis: redis

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- script: |
    curl localhost:3306
    curl localhost:6379
    echo $AGENT_SERVICES_REDIS_PORTS_6379
    echo running docker ???

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'
